

services:
  backend:
    build: ./backend
    container_name: sepsa-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/.venv
      - C:\Users\dhruw\.deepface:/root/.deepface
    environment:
      - TF_ENABLE_ONEDNN_OPTS=0
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    container_name: sepsa-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

  admin-panel:
    build: ./backend
    container_name: sepsa-admin
    ports:
      - "8501:8501"
    volumes:
      - ./backend:/app
      - ./backend/storage:/app/storage
    environment:
      - STREAMLIT_SERVER_PORT=8501
    command: streamlit run admin_panel.py --server.port 8501 --server.address 0.0.0.0